[package]
name = "tarpc"
version = "0.1.0"
authors = ["Adam Wright <adam.austin.wright@gmail.com>", "Tim Kuehn <timothy.j.kuehn@gmail.com>"]
license = "MIT"
description = "tarpc is an RPC framework for rust with a focus on ease of use."

[dependencies]
bincode = "*"
env_logger = "*"
lazy_static = "*"
log = "*"
scoped-pool = "*"
serde = "*"
serde_macros = "*"
