[package]
name = "tarpc"
version = "0.1.0"
authors = ["Adam Wright <adam.austin.wright@gmail.com>", "Tim Kuehn <timothy.j.kuehn@gmail.com>"]
license = "MIT"
documentation = "https://google.github.io/tarpc"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "protocol", "framework", "remote", "procedure", "serialize"]
readme = "README.md"
description = "An RPC framework for Rust with a focus on ease of use."

[dependencies]
bincode = "*"
env_logger = "*"
lazy_static = "*"
log = "*"
scoped-pool = "*"
serde = "*"
serde_macros = "*"
